apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # Substitua pelo base64 da sua senha real:
  # echo -n "superpassword" | base64
  # echo -n "ASIA2RJFTLHEK74I2FGF" | base64
  user-password: QVNJQTJSSkZUTEhFSzc0STJGR0Y=