apiVersion: v1
kind: Service
metadata:
  name: fiap-rocks-server
spec:
  selector:
    app: fiap-rocks-server
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8083
    - name: custom-port
      port: 30080
      targetPort: 8083