apiVersion: v1
kind: Service
metadata:
  name: fiap-rocks-server
spec:
  selector:
    app: fiap-rocks-server
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8083
    nodePort: 30080    # Porta exposta no Node (opcional, para tipo NodePort)