apiVersion: v1
kind: Service
metadata:
  name: fiap-rocks-server
spec:
  selector:
    app: fiap-rocks-server
  type: NodePort
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
    nodePort: 30080  # Porta entre 30000-32767
